dist: trusty
sudo: false
addons:
  chrome: stable
language: node_js
node_js: node

install:
- npm ci
cache:
  directories:
  - $HOME/.npm
script:
- npm run test-lib-ci
- npm run build-lib && npm run build

notifications:
  email: false

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist/angular-treant-demo
  on:
    branch: master

git:
  depth: 3

after_success:
  - npm run travis-deploy-once "npm run semantic-release"

branches:
  except:
    - /^v\d+\.\d+\.\d+$/